#!/usr/bin/python
import random

MAX = 32


colors = (random.randint(0, MAX / 2),
          random.randint(0, MAX),
          random.randint(0, MAX))

print "\033]6;1;bg;red;brightness;%s\a" % (colors[0] * 3 + 100),
print "\033]6;1;bg;green;brightness;%s\a" % (colors[1] * 3 + 100),
print "\033]6;1;bg;blue;brightness;%s\a" % (colors[2] * 3 + 100),
print "\033]Ph%02x%02x%02x\033\\" % colors,
