#!/usr/bin/python
import random

r_min, r_max = 5, 24
g_min, g_max = 5, 48
b_min, b_max = 5, 48

#MAX = 32


colors = (random.randint(r_min, r_max),
          random.randint(g_min, g_max),
          random.randint(b_min, b_max))

print "\033]6;1;bg;red;brightness;%s\a" % (colors[0] * 3 + 100),
print "\033]6;1;bg;green;brightness;%s\a" % (colors[1] * 3 + 100),
print "\033]6;1;bg;blue;brightness;%s\a" % (colors[2] * 3 + 100),
print "\033]Ph%02x%02x%02x\033\\" % colors,
